[versions]
androidGradlePlugin = "8.2.2"
compose = "1.6.1"
lifecycle = "2.7.0"
material3 = "1.2.0"

[libraries]
gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }

core-ktx = {group = "androidx.core", name = "core-ktx", version = "1.12.0"}
activity = { group = "androidx.activity", name = "activity-compose", version = "1.8.2" }
lifecycle-runtime-ktx = {group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle"}
navigation = { group = "androidx.navigation", name = "navigation-compose", version = "2.7.7" }

compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-graphics = {group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose"}
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }

material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

junit = { group = "junit", name = "junit", version = "4.13.2" }